# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "65db6ab1bb2732a3786913bb4c781808"
name = "Price Engine"
application_url = "https://price-engine-sepia.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://price-engine-sepia.vercel.app/auth/callback" ]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/app/compliance"

[build]
automatically_update_urls_on_dev = false



